name: Node CI
on:
  push:
    branches :
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x, 12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name : install yarn
      run : |
        curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
        echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
        sudo apt-get update && sudo apt-get install yarn
    - name: npm install, build, and test
      run: |
        yarn install
        yarn build --if-present
        yarn test
    - name : create release 
      - uses: actions/checkout@v1
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "dist/*"
          bodyFile: "changelog.md"
          # This token will be deleted once I can access secrets. Do not fear child
          #token: ${{ secrets.GITHUB_TOKEN }}
          token : "843b6932e22313f70ca031c9732b3c7974a206c5"
     
      env:
        CI: true
